[build]
  command = "mkdir -p netlify/functions"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "danmu_api/sources/renren.js,danmu_api/sources/iqiyi.js"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200